services:

  mongodb:
    image: mongo:8.2.4
    container_name: mongodb
    ports:
      - "32768:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  mongodb_data:
    driver: local